# Site settings
title: Zachary
subtitle: Berardo
email: me@zacharyberardo.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zacharyberardo.com" # the base hostname & protocol for your site, e.g. http://example.com

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url: http://github.com/zachnthebox
gitlab_url:
googleplus_url:
instagram_url: https://instagram.com/zachnthebox
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/zachnthebox

# Build settings
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
